name: Build

on:
  push:
    branches:
      - main
      - master
      - releases/**
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          path: vgeekpro
      - uses: actions/setup-node@v4
        name: Install Node
        with:
          node-version: latest
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
          version: latest
      - name: Install Packages
        run: |
          cd ${{ github.workspace }}/vgeekpro
          pnpm install --frozen-lockfile --color
      - name: Build Static Files
        run: |
          cd ${{ github.workspace }}/vgeekpro
          pnpm generate
          cp -R ${{ github.workspace }}/vgeekpro/.output/public/ ${{ github.workspace }}/static
          rm -R ${{ github.workspace }}/vgeekpro/.output
      - name: Build Nitro Files
        run: |
          cd ${{ github.workspace }}/vgeekpro
          pnpm build
          cp -R ${{ github.workspace }}/vgeekpro/.output/ ${{ github.workspace }}/nitro
          rm -R ${{ github.workspace }}/vgeekpro/.output
      - name: Static Publish
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}/static
          name: VGeek Static
          compression-level: 9
      - name: Nitro Publish
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}/nitro
          name: VGeek Nitro
          compression-level: 9
