name: Build Static Files

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          path: vgeekpro
      - uses: actions/setup-node@v4
        name: Install Node
        with:
          node-version: latest
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
          version: latest
      - name: Install Packages
        run: |
          cd ${{ github.workspace }}/vgeekpro
          pnpm install --frozen-lockfile --color
      - name: Build Static Files
        run: |
          cd ${{ github.workspace }}/vgeekpro
          pnpm generate
      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}/vgeekpro/.output/public/
          name: Output
